<template><div><p>在开发过程中，<code v-pre>AUTO_INCREMENT</code> 字段在数据库中通常用作主键，自增长的 <code v-pre>id</code> 是数据库表中非常常见的设计。然而，在一些情况下，我们可能会遇到 ID 不按顺序递增的问题。今天，我们将介绍如何解决这个问题，确保数据库中的 <code v-pre>id</code> 按照顺序自增长。</p>
<h2 id="_1-问题描述" tabindex="-1"><a class="header-anchor" href="#_1-问题描述"><span>1. 问题描述</span></a></h2>
<p>我们在使用 MyBatis-Plus 插入数据时，发现数据库中的 <code v-pre>id</code> 字段并没有按照预期的顺序自增长。这种情况往往发生在数据库的字段类型不正确，或者在修改表结构时没有正确更新自增长计数器。</p>
<h2 id="_2-原因分析" tabindex="-1"><a class="header-anchor" href="#_2-原因分析"><span>2. 原因分析</span></a></h2>
<h3 id="_1-数据库字段类型不匹配" tabindex="-1"><a class="header-anchor" href="#_1-数据库字段类型不匹配"><span>1. <strong>数据库字段类型不匹配</strong></span></a></h3>
<p>在数据库中，<code v-pre>id</code> 字段的类型如果设为 <code v-pre>INT</code>，在数据量达到一定值后，会导致溢出问题。而如果 <code v-pre>id</code> 字段的值超出了 <code v-pre>INT</code> 的最大范围，就会导致插入数据时失败。为避免这一问题，应该使用 <code v-pre>BIGINT</code> 类型。</p>
<h3 id="_2-未给id字段设置-tableid-type-idtype-auto-ps-这是我的原因" tabindex="-1"><a class="header-anchor" href="#_2-未给id字段设置-tableid-type-idtype-auto-ps-这是我的原因"><span>2. <strong>未给id字段设置 @TableId(type = IdType.AUTO)(PS:这是我的原因)</strong></span></a></h3>
<h3 id="_3-未重置自增长值" tabindex="-1"><a class="header-anchor" href="#_3-未重置自增长值"><span>3. <strong>未重置自增长值</strong></span></a></h3>
<p>在某些情况下，删除数据或重建表后，数据库的自增长计数器可能会出现不连续的情况，导致新的 <code v-pre>id</code> 值跳跃。通过重置自增长计数器，可以确保 <code v-pre>id</code> 从预期的值开始增长。</p>
<h2 id="_3-解决方案" tabindex="-1"><a class="header-anchor" href="#_3-解决方案"><span>3. 解决方案</span></a></h2>
<h3 id="_1-修改数据库字段类型为-bigint" tabindex="-1"><a class="header-anchor" href="#_1-修改数据库字段类型为-bigint"><span>1. <strong>修改数据库字段类型为 <code v-pre>BIGINT</code></strong></span></a></h3>
<p>确保数据库中的 <code v-pre>id</code> 字段类型为 <code v-pre>BIGINT</code>，以支持更大的数据范围。可以使用以下 SQL 语句修改字段类型：</p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">ALTER</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> TABLE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> notice </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">MODIFY</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> COLUMN id </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">BIGINT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> AUTO_INCREMENT;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>这样可以避免 <code v-pre>INT</code> 类型导致的数据溢出问题，确保 <code v-pre>id</code> 字段的自增长顺利进行。</p>
<h3 id="_2-设置-auto-increment-起始值" tabindex="-1"><a class="header-anchor" href="#_2-设置-auto-increment-起始值"><span>2. <strong>设置 <code v-pre>AUTO_INCREMENT</code> 起始值</strong></span></a></h3>
<p>如果你希望自增长的 <code v-pre>id</code> 从某个特定值开始（比如 <code v-pre>11</code>），可以通过以下 SQL 设置起始值：</p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">ALTER</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> TABLE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> notice AUTO_INCREMENT </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 11</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_3-检查当前-auto-increment-值" tabindex="-1"><a class="header-anchor" href="#_3-检查当前-auto-increment-值"><span>3. <strong>检查当前 <code v-pre>AUTO_INCREMENT</code> 值</strong></span></a></h3>
<p>如果你不确定当前自增长计数器的值，可以通过以下命令检查：</p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">SHOW </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">TABLE</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> STATUS</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> LIKE</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 'notice'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>这将返回一个包含表状态信息的结果，其中包括当前的 <code v-pre>AUTO_INCREMENT</code> 值。在查看此值后，您可以确认自增长计数器是否设置正确。</p>
<h3 id="_4-确保-po-实体类-id-为自增长" tabindex="-1"><a class="header-anchor" href="#_4-确保-po-实体类-id-为自增长"><span>4. <strong>确保 PO 实体类 <code v-pre>id</code> 为自增长</strong></span></a></h3>
<p>在 MyBatis-Plus 中，确保实体类的主键 <code v-pre>id</code> 被设置为自增长。你可以通过在实体类中使用 <code v-pre>@TableId(type = IdType.AUTO)</code> 注解来实现这一点。示例如下：</p>
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-java"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">@</span><span style="--shiki-light:#A626A4;--shiki-dark:#E5C07B">TableId</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">type</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B"> IdType</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">AUTO</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">private</span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B"> Long</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>这将告知 MyBatis-Plus 在插入数据时，自动生成 <code v-pre>id</code> 值，而不需要手动设置。</p>
<h3 id="_5-删除数据后的自增长值重置" tabindex="-1"><a class="header-anchor" href="#_5-删除数据后的自增长值重置"><span>5. <strong>删除数据后的自增长值重置</strong></span></a></h3>
<p>如果在删除数据后发现自增长计数器没有更新，导致后续插入的 <code v-pre>id</code> 跳跃，可以使用以下 SQL 命令来重置自增长值：</p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">ALTER</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> TABLE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> notice AUTO_INCREMENT </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;  </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">-- 设置起始值为 1</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>注意，这将使得自增长计数器从 <code v-pre>1</code> 开始，确保 <code v-pre>id</code> 从预期值递增。</p>
<h2 id="_4-结论" tabindex="-1"><a class="header-anchor" href="#_4-结论"><span>4. 结论</span></a></h2>
<p>确保数据库表中的 <code v-pre>id</code> 字段类型为 <code v-pre>BIGINT</code>，避免超出 <code v-pre>INT</code> 范围导致的问题。同时，合理配置 <code v-pre>AUTO_INCREMENT</code> 起始值，确保自增长计数器从正确的位置开始。通过 MyBatis-Plus 的 <code v-pre>@TableId(type = IdType.AUTO)</code> 注解，能够保证 <code v-pre>id</code> 字段的自增长行为，并且在删除数据后，适时重置自增长值，可以避免 ID 跳跃。</p>
<p>通过这些操作，能够有效解决 <code v-pre>id</code> 不按顺序递增的问题，确保数据库操作的稳定性和数据一致性。</p>
</div></template>


