<template><div><h1 id="sql中的cte与case-when" tabindex="-1"><a class="header-anchor" href="#sql中的cte与case-when"><span>SQL中的CTE与CASE WHEN</span></a></h1>
<h2 id="cte-common-table-expression-公共表表达式" tabindex="-1"><a class="header-anchor" href="#cte-common-table-expression-公共表表达式"><span>CTE（Common Table Expression:公共表表达式）</span></a></h2>
<h3 id="概念" tabindex="-1"><a class="header-anchor" href="#概念"><span>概念</span></a></h3>
<p>CTE是一种临时命名的查询结果集，它允许我们在一个查询语句中多次引用。CTE在查询语句中定义，仅在该查询语句执行期间存在，就像是一个临时搭建的“舞台”，专门为当前查询服务。CTE通常用于简化复杂的查询，将一个大的查询逻辑拆分成多个小的、可管理的部分，从而提高查询的可读性和可维护性。</p>
<h3 id="语法结构" tabindex="-1"><a class="header-anchor" href="#语法结构"><span>语法结构</span></a></h3>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">WITH</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> cte_name </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">AS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    SELECT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ...  </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">-- CTE的查询逻辑，定义这个临时结果集的内容</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">SELECT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ... </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> cte_name;  </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">-- 在主查询中使用CTE，就像使用一个普通的表一样</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>其中，<code v-pre>cte_name</code>是我们给这个CTE取的名字，方便在后续查询中引用；<code v-pre>SELECT...</code>部分是定义CTE结果集的具体查询语句。需要注意的是，CTE定义之后，必须紧接着一个使用它的SQL语句（如<code v-pre>SELECT</code>、<code v-pre>INSERT</code>、<code v-pre>UPDATE</code>、<code v-pre>DELETE</code>等）。</p>
<h3 id="核心场景" tabindex="-1"><a class="header-anchor" href="#核心场景"><span>核心场景</span></a></h3>
<ol>
<li><strong>递归查询</strong>：在处理树形结构数据时，递归CTE尤为重要。</li>
</ol>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">WITH</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> RECURSIVE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> cte_name </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">AS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">    -- 锚点查询（基础情况）</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    SELECT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ...</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ...</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    WHERE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ...  </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">-- 通常定义根节点条件</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    </span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    UNION ALL</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    </span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">    -- 递归查询（迭代情况）</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    SELECT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ...</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> cte_name  </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">-- 关键：引用自身</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    JOIN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ...       </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">-- 通过 JOIN 连接原始表或其他表</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    WHERE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ...      </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">-- 控制递归终止条件</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">SELECT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> * </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> cte_name;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li><strong>多步骤计算</strong>：当一个查询需要进行多个步骤的计算时，CTE可以将每个步骤的结果临时存储，方便后续步骤使用。例如，在分析销售数据时，先计算每个月的总销售额，再找出总销售额高于平均水平的月份。</li>
</ol>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">WITH</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> MonthlySales </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">AS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    SELECT</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> month</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">SUM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(sales) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">AS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> total_sales</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> orders </span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    GROUP BY</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> month</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">),</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">TopMonths </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">AS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    SELECT</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> month</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, total_sales</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> MonthlySales </span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    WHERE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> total_sales </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">></span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">SELECT</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> AVG</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(total_sales) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> MonthlySales)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">SELECT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> * </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> TopMonths;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在这个例子中，<code v-pre>MonthlySales</code> CTE计算了每个月的总销售额，<code v-pre>TopMonths</code> CTE则基于<code v-pre>MonthlySales</code>的结果筛选出总销售额高于平均水平的月份。</p>
<h3 id="优点" tabindex="-1"><a class="header-anchor" href="#优点"><span>优点</span></a></h3>
<ol>
<li><strong>代码模块化</strong>：将复杂查询拆分成多个CTE，每个CTE专注于一个特定的逻辑，使代码结构更清晰，易于理解和维护。</li>
<li><strong>支持递归</strong>：能够轻松处理层级数据，这是传统子查询难以做到的。</li>
<li><strong>可多次引用</strong>：在同一查询中，可以多次引用同一个CTE，避免了重复编写相同的查询逻辑。</li>
</ol>
<h2 id="case-when" tabindex="-1"><a class="header-anchor" href="#case-when"><span>CASE WHEN</span></a></h2>
<h3 id="概念-1" tabindex="-1"><a class="header-anchor" href="#概念-1"><span>概念</span></a></h3>
<p>CASE WHEN是SQL中的条件表达式，用于在查询中实现逻辑判断，类似于编程语言中的<code v-pre>if - else</code>语句。它允许我们根据不同的条件返回不同的结果，为查询增加了灵活性。</p>
<h3 id="语法结构-1" tabindex="-1"><a class="header-anchor" href="#语法结构-1"><span>语法结构</span></a></h3>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">CASE</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    WHEN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> condition1 </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">THEN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> result1</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    WHEN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> condition2 </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">THEN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> result2</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">   ...</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    ELSE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> default_result</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">END</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>其中，<code v-pre>condition1</code>、<code v-pre>condition2</code>等是布尔表达式，当<code v-pre>condition1</code>为<code v-pre>true</code>时，返回<code v-pre>result1</code>；当<code v-pre>condition1</code>为<code v-pre>false</code>，而<code v-pre>condition2</code>为<code v-pre>true</code>时，返回<code v-pre>result2</code>；以此类推。如果所有条件都不满足，则返回<code v-pre>ELSE</code>后面的<code v-pre>default_result</code>（<code v-pre>ELSE</code>子句是可选的，如果省略，当所有条件都不满足时返回<code v-pre>NULL</code>）。</p>
<h3 id="核心场景-1" tabindex="-1"><a class="header-anchor" href="#核心场景-1"><span>核心场景</span></a></h3>
<ol>
<li><strong>数据分类</strong>：对数据进行分类是CASE WHEN的常见应用。例如，根据商品价格将商品分为“高价”“中价”“低价”三类。</li>
</ol>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">SELECT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    product_name,</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    price,</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    CASE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">        WHEN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> price </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">></span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 100</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> THEN</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> '高价'</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">        WHEN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> price </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">></span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 50</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> THEN</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> '中价'</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">        ELSE</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> '低价'</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    END</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> AS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> price_category</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> products;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li><strong>条件聚合</strong>：在聚合函数中使用CASE WHEN可以实现条件聚合。比如，统计员工表中每个部门的男女人数。</li>
</ol>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">SELECT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    department,</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">    SUM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">CASE</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> WHEN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> gender </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 'M'</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> THEN</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> ELSE</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> END</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">AS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> male_count,</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">    SUM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">CASE</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> WHEN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> gender </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 'F'</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> THEN</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> ELSE</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> END</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">AS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> female_count</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> employees </span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">GROUP BY</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> department;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="3">
<li><strong>数据转换</strong>：可以利用CASE WHEN进行数据转换。例如，将订单日期转换为更易读的“今年订单”“去年订单”等形式。</li>
</ol>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">SELECT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    order_id,</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    order_date,</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    CASE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">        WHEN</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> order_date </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">>=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> '2023 - 01 - 01'</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> THEN</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> '今年订单'</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">        ELSE</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> '去年订单'</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    END</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> AS</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> order_period</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">FROM</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> orders;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="优点-1" tabindex="-1"><a class="header-anchor" href="#优点-1"><span>优点</span></a></h3>
<ol>
<li><strong>灵活处理行级条件逻辑</strong>：可以针对每一行数据进行条件判断和结果返回，适用于各种复杂的业务逻辑。</li>
<li><strong>可在多个子句中使用</strong>：不仅可以在<code v-pre>SELECT</code>子句中使用，还可以在<code v-pre>WHERE</code>、<code v-pre>GROUP BY</code>等子句中使用，增加了查询的灵活性。</li>
<li><strong>替代复杂的JOIN或子查询</strong>：在某些情况下，使用CASE WHEN可以避免复杂的JOIN操作或多层子查询，使查询更加简洁高效。</li>
</ol>
</div></template>


